<?php

/*Icon Themify Icons List */
$options = '  
<option value=""></option> 
<option value="ti-arrow-up">&lt;i class="ti-arrow-up"&lt;/i> ti-arrow-up </option>
<option value="ti-arrow-up">&lt;i class="ti-arrow-up"&lt;/i> ti-arrow-up </option>
<option value="ti-arrow-left">&lt;i class="ti-arrow-left"&lt;/i> ti-arrow-left </option>
<option value="ti-arrow-down">&lt;i class="ti-arrow-down"&lt;/i> ti-arrow-down </option>
<option value="ti-arrows-vertical">&lt;i class="ti-arrows-vertical"&lt;/i> ti-arrows-vertical </option>
<option value="ti-arrows-horizontal">&lt;i class="ti-arrows-horizontal"&lt;/i> ti-arrows-horizontal </option>
<option value="ti-angle-up">&lt;i class="ti-angle-up"&lt;/i> ti-angle-up </option>
<option value="ti-angle-right">&lt;i class="ti-angle-right"&lt;/i> ti-angle-right </option>
<option value="ti-angle-left">&lt;i class="ti-angle-left"&lt;/i> ti-angle-left </option>
<option value="ti-angle-down">&lt;i class="ti-angle-down"&lt;/i> ti-angle-down </option>
<option value="ti-angle-double-up">&lt;i class="ti-angle-double-up"&lt;/i> ti-angle-double-up </option>
<option value="ti-angle-double-right">&lt;i class="ti-angle-double-right"&lt;/i> ti-angle-double-right </option>
<option value="ti-angle-double-left">&lt;i class="ti-angle-double-left"&lt;/i> ti-angle-double-left </option>
<option value="ti-angle-double-down">&lt;i class="ti-angle-double-down"&lt;/i> ti-angle-double-down </option>
<option value="ti-move">&lt;i class="ti-move"&lt;/i> ti-move </option>
<option value="ti-fullscreen">&lt;i class="ti-fullscreen"&lt;/i> ti-fullscreen </option>
<option value="ti-arrow-top-right">&lt;i class="ti-arrow-top-right"&lt;/i> ti-arrow-top-right </option>
<option value="ti-arrow-top-left">&lt;i class="ti-arrow-top-left"&lt;/i> ti-arrow-top-left </option>
<option value="ti-arrow-circle-up">&lt;i class="ti-arrow-circle-up"&lt;/i> ti-arrow-circle-up </option>
<option value="ti-arrow-circle-right">&lt;i class="ti-arrow-circle-right"&lt;/i> ti-arrow-circle-right </option>
<option value="ti-arrow-circle-left">&lt;i class="ti-arrow-circle-left"&lt;/i> ti-arrow-circle-left </option>
<option value="ti-arrow-circle-down">&lt;i class="ti-arrow-circle-down"&lt;/i> ti-arrow-circle-down </option>
<option value="ti-arrows-corner">&lt;i class="ti-arrows-corner"&lt;/i> ti-arrows-corner </option>
<option value="ti-split-v">&lt;i class="ti-split-v"&lt;/i> ti-split-v </option>
<option value="ti-split-v-alt">&lt;i class="ti-split-v-alt"&lt;/i> ti-split-v-alt </option>
<option value="ti-split-h">&lt;i class="ti-split-h"&lt;/i> ti-split-h </option>
<option value="ti-hand-point-up">&lt;i class="ti-hand-point-up"&lt;/i> ti-hand-point-up </option>
<option value="ti-hand-point-right">&lt;i class="ti-hand-point-right"&lt;/i> ti-hand-point-right </option>
<option value="ti-hand-point-left">&lt;i class="ti-hand-point-left"&lt;/i> ti-hand-point-left </option>
<option value="ti-hand-point-down">&lt;i class="ti-hand-point-down"&lt;/i> ti-hand-point-down </option>
<option value="ti-back-right">&lt;i class="ti-back-right"&lt;/i> ti-back-right </option>
<option value="ti-back-left">&lt;i class="ti-back-left"&lt;/i> ti-back-left </option>
<option value="ti-exchange-vertical">&lt;i class="ti-exchange-vertical"&lt;/i> ti-exchange-vertical </option>
<option value="ti-wand">&lt;i class="ti-wand"&lt;/i> ti-wand </option>
<option value="ti-save">&lt;i class="ti-save"&lt;/i> ti-save </option>
<option value="ti-save-alt">&lt;i class="ti-save-alt"&lt;/i> ti-save-alt </option>
<option value="ti-direction">&lt;i class="ti-direction"&lt;/i> ti-direction </option>
<option value="ti-direction-alt">&lt;i class="ti-direction-alt"&lt;/i> ti-direction-alt </option>
<option value="ti-user">&lt;i class="ti-user"&lt;/i> ti-user </option>
<option value="ti-link">&lt;i class="ti-link"&lt;/i> ti-link </option>
<option value="ti-unlink">&lt;i class="ti-unlink"&lt;/i> ti-unlink </option>
<option value="ti-trash">&lt;i class="ti-trash"&lt;/i> ti-trash </option>
<option value="ti-target">&lt;i class="ti-target"&lt;/i> ti-target </option>
<option value="ti-tag">&lt;i class="ti-tag"&lt;/i> ti-tag </option>
<option value="ti-desktop">&lt;i class="ti-desktop"&lt;/i> ti-desktop </option>
<option value="ti-tablet">&lt;i class="ti-tablet"&lt;/i> ti-tablet </option>
<option value="ti-mobile">&lt;i class="ti-mobile"&lt;/i> ti-mobile </option>
<option value="ti-email">&lt;i class="ti-email"&lt;/i> ti-email </option>
<option value="ti-star">&lt;i class="ti-star"&lt;/i> ti-star </option>
<option value="ti-spray">&lt;i class="ti-spray"&lt;/i> ti-spray </option>
<option value="ti-signal">&lt;i class="ti-signal"&lt;/i> ti-signal </option>
<option value="ti-shopping-cart">&lt;i class="ti-shopping-cart"&lt;/i> ti-shopping-cart </option>
<option value="ti-shopping-cart-full">&lt;i class="ti-shopping-cart-full"&lt;/i> ti-shopping-cart-full </option>
<option value="ti-settings">&lt;i class="ti-settings"&lt;/i> ti-settings </option>
<option value="ti-search">&lt;i class="ti-search"&lt;/i> ti-search </option>
<option value="ti-zoom-in">&lt;i class="ti-zoom-in"&lt;/i> ti-zoom-in </option>
<option value="ti-zoom-out">&lt;i class="ti-zoom-out"&lt;/i> ti-zoom-out </option>
<option value="ti-cut">&lt;i class="ti-cut"&lt;/i> ti-cut </option>
<option value="ti-ruler">&lt;i class="ti-ruler"&lt;/i> ti-ruler </option>
<option value="ti-ruler-alt-2">&lt;i class="ti-ruler-alt-2"&lt;/i> ti-ruler-alt-2 </option>
<option value="ti-ruler-pencil">&lt;i class="ti-ruler-pencil"&lt;/i> ti-ruler-pencil </option>
<option value="ti-ruler-alt">&lt;i class="ti-ruler-alt"&lt;/i> ti-ruler-alt </option>
<option value="ti-bookmark">&lt;i class="ti-bookmark"&lt;/i> ti-bookmark </option>
<option value="ti-bookmark-alt">&lt;i class="ti-bookmark-alt"&lt;/i> ti-bookmark-alt </option>
<option value="ti-reload">&lt;i class="ti-reload"&lt;/i> ti-reload </option>
<option value="ti-plus">&lt;i class="ti-plus"&lt;/i> ti-plus </option>
<option value="ti-minus">&lt;i class="ti-minus"&lt;/i> ti-minus </option>
<option value="ti-close">&lt;i class="ti-close"&lt;/i> ti-close </option>
<option value="ti-pin">&lt;i class="ti-pin"&lt;/i> ti-pin </option>
<option value="ti-pencil">&lt;i class="ti-pencil"&lt;/i> ti-pencil </option>
<option value="ti-pencil-alt">&lt;i class="ti-pencil-alt"&lt;/i> ti-pencil-alt </option>
<option value="ti-paint-roller">&lt;i class="ti-paint-roller"&lt;/i> ti-paint-roller </option>
<option value="ti-paint-bucket">&lt;i class="ti-paint-bucket"&lt;/i> ti-paint-bucket </option>
<option value="ti-na">&lt;i class="ti-na"&lt;/i> ti-na </option>
<option value="ti-medall">&lt;i class="ti-medall"&lt;/i> ti-medall </option>
<option value="ti-medall-alt">&lt;i class="ti-medall-alt"&lt;/i> ti-medall-alt </option>
<option value="ti-marker">&lt;i class="ti-marker"&lt;/i> ti-marker </option>
<option value="ti-marker-alt">&lt;i class="ti-marker-alt"&lt;/i> ti-marker-alt </option>
<option value="ti-lock">&lt;i class="ti-lock"&lt;/i> ti-lock </option>
<option value="ti-unlock">&lt;i class="ti-unlock"&lt;/i> ti-unlock </option>
<option value="ti-location-arrow">&lt;i class="ti-location-arrow"&lt;/i> ti-location-arrow </option>
<option value="ti-layout">&lt;i class="ti-layout"&lt;/i> ti-layout </option>
<option value="ti-layers">&lt;i class="ti-layers"&lt;/i> ti-layers </option>
<option value="ti-layers-alt">&lt;i class="ti-layers-alt"&lt;/i> ti-layers-alt </option>
<option value="ti-key">&lt;i class="ti-key"&lt;/i> ti-key </option>
<option value="ti-image">&lt;i class="ti-image"&lt;/i> ti-image </option>
<option value="ti-heart">&lt;i class="ti-heart"&lt;/i> ti-heart </option>
<option value="ti-heart-broken">&lt;i class="ti-heart-broken"&lt;/i> ti-heart-broken </option>
<option value="ti-hand-stop">&lt;i class="ti-hand-stop"&lt;/i> ti-hand-stop </option>
<option value="ti-hand-open">&lt;i class="ti-hand-open"&lt;/i> ti-hand-open </option>
<option value="ti-hand-drag">&lt;i class="ti-hand-drag"&lt;/i> ti-hand-drag </option>
<option value="ti-flag">&lt;i class="ti-flag"&lt;/i> ti-flag </option>
<option value="ti-flag-alt">&lt;i class="ti-flag-alt"&lt;/i> ti-flag-alt </option>
<option value="ti-flag-alt-2">&lt;i class="ti-flag-alt-2"&lt;/i> ti-flag-alt-2 </option>
<option value="ti-eye">&lt;i class="ti-eye"&lt;/i> ti-eye </option>
<option value="ti-import">&lt;i class="ti-import"&lt;/i> ti-import </option>
<option value="ti-export">&lt;i class="ti-export"&lt;/i> ti-export </option>
<option value="ti-cup">&lt;i class="ti-cup"&lt;/i> ti-cup </option>
<option value="ti-crown">&lt;i class="ti-crown"&lt;/i> ti-crown </option>
<option value="ti-comments">&lt;i class="ti-comments"&lt;/i> ti-comments </option>
<option value="ti-comment">&lt;i class="ti-comment"&lt;/i> ti-comment </option>
<option value="ti-comment-alt">&lt;i class="ti-comment-alt"&lt;/i> ti-comment-alt </option>
<option value="ti-thought">&lt;i class="ti-thought"&lt;/i> ti-thought </option>
<option value="ti-clip">&lt;i class="ti-clip"&lt;/i> ti-clip </option>
<option value="ti-check">&lt;i class="ti-check"&lt;/i> ti-check </option>
<option value="ti-check-box">&lt;i class="ti-check-box"&lt;/i> ti-check-box </option>
<option value="ti-camera">&lt;i class="ti-camera"&lt;/i> ti-camera </option>
<option value="ti-announcement">&lt;i class="ti-announcement"&lt;/i> ti-announcement </option>
<option value="ti-brush">&lt;i class="ti-brush"&lt;/i> ti-brush </option>
<option value="ti-brush-alt">&lt;i class="ti-brush-alt"&lt;/i> ti-brush-alt </option>
<option value="ti-palette">&lt;i class="ti-palette"&lt;/i> ti-palette </option>
<option value="ti-briefcase">&lt;i class="ti-briefcase"&lt;/i> ti-briefcase </option>
<option value="ti-bolt">&lt;i class="ti-bolt"&lt;/i> ti-bolt </option>
<option value="ti-bolt-alt">&lt;i class="ti-bolt-alt"&lt;/i> ti-bolt-alt </option>
<option value="ti-blackboard">&lt;i class="ti-blackboard"&lt;/i> ti-blackboard </option>
<option value="ti-bag">&lt;i class="ti-bag"&lt;/i> ti-bag </option>
<option value="ti-world">&lt;i class="ti-world"&lt;/i> ti-world </option>
<option value="ti-wheelchair">&lt;i class="ti-wheelchair"&lt;/i> ti-wheelchair </option>
<option value="ti-car">&lt;i class="ti-car"&lt;/i> ti-car </option>
<option value="ti-truck">&lt;i class="ti-truck"&lt;/i> ti-truck </option>
<option value="ti-timer">&lt;i class="ti-timer"&lt;/i> ti-timer </option>
<option value="ti-ticket">&lt;i class="ti-ticket"&lt;/i> ti-ticket </option>
<option value="ti-thumb-up">&lt;i class="ti-thumb-up"&lt;/i> ti-thumb-up </option>
<option value="ti-thumb-down">&lt;i class="ti-thumb-down"&lt;/i> ti-thumb-down </option>
<option value="ti-stats-up">&lt;i class="ti-stats-up"&lt;/i> ti-stats-up </option>
<option value="ti-stats-down">&lt;i class="ti-stats-down"&lt;/i> ti-stats-down </option>
<option value="ti-shine">&lt;i class="ti-shine"&lt;/i> ti-shine </option>
<option value="ti-shift-right">&lt;i class="ti-shift-right"&lt;/i> ti-shift-right </option>
<option value="ti-shift-left">&lt;i class="ti-shift-left"&lt;/i> ti-shift-left </option>
<option value="ti-shift-right-alt">&lt;i class="ti-shift-right-alt"&lt;/i> ti-shift-right-alt </option>
<option value="ti-shift-left-alt">&lt;i class="ti-shift-left-alt"&lt;/i> ti-shift-left-alt </option>
<option value="ti-shield">&lt;i class="ti-shield"&lt;/i> ti-shield </option>
<option value="ti-notepad">&lt;i class="ti-notepad"&lt;/i> ti-notepad </option>
<option value="ti-server">&lt;i class="ti-server"&lt;/i> ti-server </option>
<option value="ti-pulse">&lt;i class="ti-pulse"&lt;/i> ti-pulse </option>
<option value="ti-printer">&lt;i class="ti-printer"&lt;/i> ti-printer </option>
<option value="ti-power-off">&lt;i class="ti-power-off"&lt;/i> ti-power-off </option>
<option value="ti-plug">&lt;i class="ti-plug"&lt;/i> ti-plug </option>
<option value="ti-pie-chart">&lt;i class="ti-pie-chart"&lt;/i> ti-pie-chart </option>
<option value="ti-panel">&lt;i class="ti-panel"&lt;/i> ti-panel </option>
<option value="ti-package">&lt;i class="ti-package"&lt;/i> ti-package </option>
<option value="ti-music">&lt;i class="ti-music"&lt;/i> ti-music </option>
<option value="ti-music-alt">&lt;i class="ti-music-alt"&lt;/i> ti-music-alt </option>
<option value="ti-mouse">&lt;i class="ti-mouse"&lt;/i> ti-mouse </option>
<option value="ti-mouse-alt">&lt;i class="ti-mouse-alt"&lt;/i> ti-mouse-alt </option>
<option value="ti-money">&lt;i class="ti-money"&lt;/i> ti-money </option>
<option value="ti-microphone">&lt;i class="ti-microphone"&lt;/i> ti-microphone </option>
<option value="ti-menu">&lt;i class="ti-menu"&lt;/i> ti-menu </option>
<option value="ti-menu-alt">&lt;i class="ti-menu-alt"&lt;/i> ti-menu-alt </option>
<option value="ti-map">&lt;i class="ti-map"&lt;/i> ti-map </option>
<option value="ti-map-alt">&lt;i class="ti-map-alt"&lt;/i> ti-map-alt </option>
<option value="ti-location-pin">&lt;i class="ti-location-pin"&lt;/i> ti-location-pin </option>
<option value="ti-light-bulb">&lt;i class="ti-light-bulb"&lt;/i> ti-light-bulb </option>
<option value="ti-info">&lt;i class="ti-info"&lt;/i> ti-info </option>
<option value="ti-infinite">&lt;i class="ti-infinite"&lt;/i> ti-infinite </option>
<option value="ti-id-badge">&lt;i class="ti-id-badge"&lt;/i> ti-id-badge </option>
<option value="ti-hummer">&lt;i class="ti-hummer"&lt;/i> ti-hummer </option>
<option value="ti-home">&lt;i class="ti-home"&lt;/i> ti-home </option>
<option value="ti-help">&lt;i class="ti-help"&lt;/i> ti-help </option>
<option value="ti-headphone">&lt;i class="ti-headphone"&lt;/i> ti-headphone </option>
<option value="ti-harddrives">&lt;i class="ti-harddrives"&lt;/i> ti-harddrives </option>
<option value="ti-harddrive">&lt;i class="ti-harddrive"&lt;/i> ti-harddrive </option>
<option value="ti-gift">&lt;i class="ti-gift"&lt;/i> ti-gift </option>
<option value="ti-game">&lt;i class="ti-game"&lt;/i> ti-game </option>
<option value="ti-filter">&lt;i class="ti-filter"&lt;/i> ti-filter </option>
<option value="ti-files">&lt;i class="ti-files"&lt;/i> ti-files </option>
<option value="ti-file">&lt;i class="ti-file"&lt;/i> ti-file </option>
<option value="ti-zip">&lt;i class="ti-zip"&lt;/i> ti-zip </option>
<option value="ti-folder">&lt;i class="ti-folder"&lt;/i> ti-folder </option>
<option value="ti-envelope">&lt;i class="ti-envelope"&lt;/i> ti-envelope </option>
<option value="ti-dashboard">&lt;i class="ti-dashboard"&lt;/i> ti-dashboard </option>
<option value="ti-cloud">&lt;i class="ti-cloud"&lt;/i> ti-cloud </option>
<option value="ti-cloud-up">&lt;i class="ti-cloud-up"&lt;/i> ti-cloud-up </option>
<option value="ti-cloud-down">&lt;i class="ti-cloud-down"&lt;/i> ti-cloud-down </option>
<option value="ti-clipboard">&lt;i class="ti-clipboard"&lt;/i> ti-clipboard </option>
<option value="ti-calendar">&lt;i class="ti-calendar"&lt;/i> ti-calendar </option>
<option value="ti-book">&lt;i class="ti-book"&lt;/i> ti-book </option>
<option value="ti-bell">&lt;i class="ti-bell"&lt;/i> ti-bell </option>
<option value="ti-basketball">&lt;i class="ti-basketball"&lt;/i> ti-basketball </option>
<option value="ti-bar-chart">&lt;i class="ti-bar-chart"&lt;/i> ti-bar-chart </option>
<option value="ti-bar-chart-alt">&lt;i class="ti-bar-chart-alt"&lt;/i> ti-bar-chart-alt </option>
<option value="ti-archive">&lt;i class="ti-archive"&lt;/i> ti-archive </option>
<option value="ti-anchor">&lt;i class="ti-anchor"&lt;/i> ti-anchor </option>
<option value="ti-alert">&lt;i class="ti-alert"&lt;/i> ti-alert </option>
<option value="ti-alarm-clock">&lt;i class="ti-alarm-clock"&lt;/i> ti-alarm-clock </option>
<option value="ti-agenda">&lt;i class="ti-agenda"&lt;/i> ti-agenda </option>
<option value="ti-write">&lt;i class="ti-write"&lt;/i> ti-write </option>
<option value="ti-wallet">&lt;i class="ti-wallet"&lt;/i> ti-wallet </option>
<option value="ti-video-clapper">&lt;i class="ti-video-clapper"&lt;/i> ti-video-clapper </option>
<option value="ti-video-camera">&lt;i class="ti-video-camera"&lt;/i> ti-video-camera </option>
<option value="ti-vector">&lt;i class="ti-vector"&lt;/i> ti-vector </option>
<option value="ti-support">&lt;i class="ti-support"&lt;/i> ti-support </option>
<option value="ti-stamp">&lt;i class="ti-stamp"&lt;/i> ti-stamp </option>
<option value="ti-slice">&lt;i class="ti-slice"&lt;/i> ti-slice </option>
<option value="ti-shortcode">&lt;i class="ti-shortcode"&lt;/i> ti-shortcode </option>
<option value="ti-receipt">&lt;i class="ti-receipt"&lt;/i> ti-receipt </option>
<option value="ti-pin2">&lt;i class="ti-pin2"&lt;/i> ti-pin2 </option>
<option value="ti-pin-alt">&lt;i class="ti-pin-alt"&lt;/i> ti-pin-alt </option>
<option value="ti-pencil-alt2">&lt;i class="ti-pencil-alt2"&lt;/i> ti-pencil-alt2 </option>
<option value="ti-eraser">&lt;i class="ti-eraser"&lt;/i> ti-eraser </option>
<option value="ti-more">&lt;i class="ti-more"&lt;/i> ti-more </option>
<option value="ti-more-alt">&lt;i class="ti-more-alt"&lt;/i> ti-more-alt </option>
<option value="ti-microphone-alt">&lt;i class="ti-microphone-alt"&lt;/i> ti-microphone-alt </option>
<option value="ti-magnet">&lt;i class="ti-magnet"&lt;/i> ti-magnet </option>
<option value="ti-line-double">&lt;i class="ti-line-double"&lt;/i> ti-line-double </option>
<option value="ti-line-dotted">&lt;i class="ti-line-dotted"&lt;/i> ti-line-dotted </option>
<option value="ti-line-dashed">&lt;i class="ti-line-dashed"&lt;/i> ti-line-dashed </option>
<option value="ti-ink-pen">&lt;i class="ti-ink-pen"&lt;/i> ti-ink-pen </option>
<option value="ti-info-alt">&lt;i class="ti-info-alt"&lt;/i> ti-info-alt </option>
<option value="ti-help-alt">&lt;i class="ti-help-alt"&lt;/i> ti-help-alt </option>
<option value="ti-headphone-alt">&lt;i class="ti-headphone-alt"&lt;/i> ti-headphone-alt </option>
<option value="ti-gallery">&lt;i class="ti-gallery"&lt;/i> ti-gallery </option>
<option value="ti-face-smile">&lt;i class="ti-face-smile"&lt;/i> ti-face-smile </option>
<option value="ti-face-sad">&lt;i class="ti-face-sad"&lt;/i> ti-face-sad </option>
<option value="ti-credit-card">&lt;i class="ti-credit-card"&lt;/i> ti-credit-card </option>
<option value="ti-comments-smiley">&lt;i class="ti-comments-smiley"&lt;/i> ti-comments-smiley </option>
<option value="ti-time">&lt;i class="ti-time"&lt;/i> ti-time </option>
<option value="ti-share">&lt;i class="ti-share"&lt;/i> ti-share </option>
<option value="ti-share-alt">&lt;i class="ti-share-alt"&lt;/i> ti-share-alt </option>
<option value="ti-rocket">&lt;i class="ti-rocket"&lt;/i> ti-rocket </option>
<option value="ti-new-window">&lt;i class="ti-new-window"&lt;/i> ti-new-window </option>
<option value="ti-rss">&lt;i class="ti-rss"&lt;/i> ti-rss </option>
<option value="ti-rss-alt">&lt;i class="ti-rss-alt"&lt;/i> ti-rss-alt </option>
<option value="ti-control-stop">&lt;i class="ti-control-stop"&lt;/i> ti-control-stop </option>
<option value="ti-control-shuffle">&lt;i class="ti-control-shuffle"&lt;/i> ti-control-shuffle </option>
<option value="ti-control-play">&lt;i class="ti-control-play"&lt;/i> ti-control-play </option>
<option value="ti-control-pause">&lt;i class="ti-control-pause"&lt;/i> ti-control-pause </option>
<option value="ti-control-forward">&lt;i class="ti-control-forward"&lt;/i> ti-control-forward </option>
<option value="ti-control-backward">&lt;i class="ti-control-backward"&lt;/i> ti-control-backward </option>
<option value="ti-volume">&lt;i class="ti-volume"&lt;/i> ti-volume </option>
<option value="ti-control-skip-forward">&lt;i class="ti-control-skip-forward"&lt;/i> ti-control-skip-forward </option>
<option value="ti-control-skip-backward">&lt;i class="ti-control-skip-backward"&lt;/i> ti-control-skip-backward </option>
<option value="ti-control-record">&lt;i class="ti-control-record"&lt;/i> ti-control-record </option>
<option value="ti-control-eject">&lt;i class="ti-control-eject"&lt;/i> ti-control-eject </option>
<option value="ti-paragraph">&lt;i class="ti-paragraph"&lt;/i> ti-paragraph </option>
<option value="ti-uppercase">&lt;i class="ti-uppercase"&lt;/i> ti-uppercase </option>
<option value="ti-underline">&lt;i class="ti-underline"&lt;/i> ti-underline </option>
<option value="ti-text">&lt;i class="ti-text"&lt;/i> ti-text </option>
<option value="ti-Italic">&lt;i class="ti-Italic"&lt;/i> ti-Italic </option>
<option value="ti-smallcap">&lt;i class="ti-smallcap"&lt;/i> ti-smallcap </option>
<option value="ti-list">&lt;i class="ti-list"&lt;/i> ti-list </option>
<option value="ti-list-ol">&lt;i class="ti-list-ol"&lt;/i> ti-list-ol </option>
<option value="ti-align-right">&lt;i class="ti-align-right"&lt;/i> ti-align-right </option>
<option value="ti-align-left">&lt;i class="ti-align-left"&lt;/i> ti-align-left </option>
<option value="ti-align-justify">&lt;i class="ti-align-justify"&lt;/i> ti-align-justify </option>
<option value="ti-align-center">&lt;i class="ti-align-center"&lt;/i> ti-align-center </option>
<option value="ti-quote-right">&lt;i class="ti-quote-right"&lt;/i> ti-quote-right </option>
<option value="ti-quote-left">&lt;i class="ti-quote-left"&lt;/i> ti-quote-left </option>
<option value="ti-layout-width-full">&lt;i class="ti-layout-width-full"&lt;/i> ti-layout-width-full </option>
<option value="ti-layout-width-default">&lt;i class="ti-layout-width-default"&lt;/i> ti-layout-width-default </option>
<option value="ti-layout-width-default-alt">&lt;i class="ti-layout-width-default-alt"&lt;/i> ti-layout-width-default-alt </option>
<option value="ti-layout-tab">&lt;i class="ti-layout-tab"&lt;/i> ti-layout-tab </option>
<option value="ti-layout-tab-window">&lt;i class="ti-layout-tab-window"&lt;/i> ti-layout-tab-window </option>
<option value="ti-layout-tab-v">&lt;i class="ti-layout-tab-v"&lt;/i> ti-layout-tab-v </option>
<option value="ti-layout-tab-min">&lt;i class="ti-layout-tab-min"&lt;/i> ti-layout-tab-min </option>
<option value="ti-layout-slider">&lt;i class="ti-layout-slider"&lt;/i> ti-layout-slider </option>
<option value="ti-layout-slider-alt">&lt;i class="ti-layout-slider-alt"&lt;/i> ti-layout-slider-alt </option>
<option value="ti-layout-sidebar-right">&lt;i class="ti-layout-sidebar-right"&lt;/i> ti-layout-sidebar-right </option>
<option value="ti-layout-sidebar-none">&lt;i class="ti-layout-sidebar-none"&lt;/i> ti-layout-sidebar-none </option>
<option value="ti-layout-sidebar-left">&lt;i class="ti-layout-sidebar-left"&lt;/i> ti-layout-sidebar-left </option>
<option value="ti-layout-placeholder">&lt;i class="ti-layout-placeholder"&lt;/i> ti-layout-placeholder </option>
<option value="ti-layout-menu">&lt;i class="ti-layout-menu"&lt;/i> ti-layout-menu </option>
<option value="ti-layout-menu-v">&lt;i class="ti-layout-menu-v"&lt;/i> ti-layout-menu-v </option>
<option value="ti-layout-menu-separated">&lt;i class="ti-layout-menu-separated"&lt;/i> ti-layout-menu-separated </option>
<option value="ti-layout-menu-full">&lt;i class="ti-layout-menu-full"&lt;/i> ti-layout-menu-full </option>
<option value="ti-layout-media-right">&lt;i class="ti-layout-media-right"&lt;/i> ti-layout-media-right </option>
<option value="ti-layout-media-right-alt">&lt;i class="ti-layout-media-right-alt"&lt;/i> ti-layout-media-right-alt </option>
<option value="ti-layout-media-overlay">&lt;i class="ti-layout-media-overlay"&lt;/i> ti-layout-media-overlay </option>
<option value="ti-layout-media-overlay-alt">&lt;i class="ti-layout-media-overlay-alt"&lt;/i> ti-layout-media-overlay-alt </option>
<option value="ti-layout-media-overlay-alt-2">&lt;i class="ti-layout-media-overlay-alt-2"&lt;/i> ti-layout-media-overlay-alt-2 </option>
<option value="ti-layout-media-left">&lt;i class="ti-layout-media-left"&lt;/i> ti-layout-media-left </option>
<option value="ti-layout-media-left-alt">&lt;i class="ti-layout-media-left-alt"&lt;/i> ti-layout-media-left-alt </option>
<option value="ti-layout-media-center">&lt;i class="ti-layout-media-center"&lt;/i> ti-layout-media-center </option>
<option value="ti-layout-media-center-alt">&lt;i class="ti-layout-media-center-alt"&lt;/i> ti-layout-media-center-alt </option>
<option value="ti-layout-list-thumb">&lt;i class="ti-layout-list-thumb"&lt;/i> ti-layout-list-thumb </option>
<option value="ti-layout-list-thumb-alt">&lt;i class="ti-layout-list-thumb-alt"&lt;/i> ti-layout-list-thumb-alt </option>
<option value="ti-layout-list-post">&lt;i class="ti-layout-list-post"&lt;/i> ti-layout-list-post </option>
<option value="ti-layout-list-large-image">&lt;i class="ti-layout-list-large-image"&lt;/i> ti-layout-list-large-image </option>
<option value="ti-layout-line-solid">&lt;i class="ti-layout-line-solid"&lt;/i> ti-layout-line-solid </option>
<option value="ti-layout-grid4">&lt;i class="ti-layout-grid4"&lt;/i> ti-layout-grid4 </option>
<option value="ti-layout-grid3">&lt;i class="ti-layout-grid3"&lt;/i> ti-layout-grid3 </option>
<option value="ti-layout-grid2">&lt;i class="ti-layout-grid2"&lt;/i> ti-layout-grid2 </option>
<option value="ti-layout-grid2-thumb">&lt;i class="ti-layout-grid2-thumb"&lt;/i> ti-layout-grid2-thumb </option>
<option value="ti-layout-cta-right">&lt;i class="ti-layout-cta-right"&lt;/i> ti-layout-cta-right </option>
<option value="ti-layout-cta-left">&lt;i class="ti-layout-cta-left"&lt;/i> ti-layout-cta-left </option>
<option value="ti-layout-cta-center">&lt;i class="ti-layout-cta-center"&lt;/i> ti-layout-cta-center </option>
<option value="ti-layout-cta-btn-right">&lt;i class="ti-layout-cta-btn-right"&lt;/i> ti-layout-cta-btn-right </option>
<option value="ti-layout-cta-btn-left">&lt;i class="ti-layout-cta-btn-left"&lt;/i> ti-layout-cta-btn-left </option>
<option value="ti-layout-column4">&lt;i class="ti-layout-column4"&lt;/i> ti-layout-column4 </option>
<option value="ti-layout-column3">&lt;i class="ti-layout-column3"&lt;/i> ti-layout-column3 </option>
<option value="ti-layout-column2">&lt;i class="ti-layout-column2"&lt;/i> ti-layout-column2 </option>
<option value="ti-layout-accordion-separated">&lt;i class="ti-layout-accordion-separated"&lt;/i> ti-layout-accordion-separated </option>
<option value="ti-layout-accordion-merged">&lt;i class="ti-layout-accordion-merged"&lt;/i> ti-layout-accordion-merged </option>
<option value="ti-layout-accordion-list">&lt;i class="ti-layout-accordion-list"&lt;/i> ti-layout-accordion-list </option>
<option value="ti-widgetized">&lt;i class="ti-widgetized"&lt;/i> ti-widgetized </option>
<option value="ti-widget">&lt;i class="ti-widget"&lt;/i> ti-widget </option>
<option value="ti-widget-alt">&lt;i class="ti-widget-alt"&lt;/i> ti-widget-alt </option>
<option value="ti-view-list">&lt;i class="ti-view-list"&lt;/i> ti-view-list </option>
<option value="ti-view-list-alt">&lt;i class="ti-view-list-alt"&lt;/i> ti-view-list-alt </option>
<option value="ti-view-grid">&lt;i class="ti-view-grid"&lt;/i> ti-view-grid </option>
<option value="ti-upload">&lt;i class="ti-upload"&lt;/i> ti-upload </option>
<option value="ti-download">&lt;i class="ti-download"&lt;/i> ti-download </option>
<option value="ti-loop">&lt;i class="ti-loop"&lt;/i> ti-loop </option>
<option value="ti-layout-sidebar-2">&lt;i class="ti-layout-sidebar-2"&lt;/i> ti-layout-sidebar-2 </option>
<option value="ti-layout-grid4-alt">&lt;i class="ti-layout-grid4-alt"&lt;/i> ti-layout-grid4-alt </option>
<option value="ti-layout-grid3-alt">&lt;i class="ti-layout-grid3-alt"&lt;/i> ti-layout-grid3-alt </option>
<option value="ti-layout-grid2-alt">&lt;i class="ti-layout-grid2-alt"&lt;/i> ti-layout-grid2-alt </option>
<option value="ti-layout-column4-alt">&lt;i class="ti-layout-column4-alt"&lt;/i> ti-layout-column4-alt </option>
<option value="ti-layout-column3-alt">&lt;i class="ti-layout-column3-alt"&lt;/i> ti-layout-column3-alt </option>
<option value="ti-layout-column2-alt">&lt;i class="ti-layout-column2-alt"&lt;/i> ti-layout-column2-alt </option>
<option value="ti-flickr">&lt;i class="ti-flickr"&lt;/i> ti-flickr </option>
<option value="ti-flickr-alt">&lt;i class="ti-flickr-alt"&lt;/i> ti-flickr-alt </option>
<option value="ti-instagram">&lt;i class="ti-instagram"&lt;/i> ti-instagram </option>
<option value="ti-google">&lt;i class="ti-google"&lt;/i> ti-google </option>
<option value="ti-github">&lt;i class="ti-github"&lt;/i> ti-github </option>
<option value="ti-facebook">&lt;i class="ti-facebook"&lt;/i> ti-facebook </option>
<option value="ti-dropbox">&lt;i class="ti-dropbox"&lt;/i> ti-dropbox </option>
<option value="ti-dropbox-alt">&lt;i class="ti-dropbox-alt"&lt;/i> ti-dropbox-alt </option>
<option value="ti-dribbble">&lt;i class="ti-dribbble"&lt;/i> ti-dribbble </option>
<option value="ti-apple">&lt;i class="ti-apple"&lt;/i> ti-apple </option>
<option value="ti-android">&lt;i class="ti-android"&lt;/i> ti-android </option>
<option value="ti-yahoo">&lt;i class="ti-yahoo"&lt;/i> ti-yahoo </option>
<option value="ti-trello">&lt;i class="ti-trello"&lt;/i> ti-trello </option>
<option value="ti-stack-overflow">&lt;i class="ti-stack-overflow"&lt;/i> ti-stack-overflow </option>
<option value="ti-soundcloud">&lt;i class="ti-soundcloud"&lt;/i> ti-soundcloud </option>
<option value="ti-sharethis">&lt;i class="ti-sharethis"&lt;/i> ti-sharethis </option>
<option value="ti-sharethis-alt">&lt;i class="ti-sharethis-alt"&lt;/i> ti-sharethis-alt </option>
<option value="ti-reddit">&lt;i class="ti-reddit"&lt;/i> ti-reddit </option>
<option value="ti-microsoft">&lt;i class="ti-microsoft"&lt;/i> ti-microsoft </option>
<option value="ti-microsoft-alt">&lt;i class="ti-microsoft-alt"&lt;/i> ti-microsoft-alt </option>
<option value="ti-linux">&lt;i class="ti-linux"&lt;/i> ti-linux </option>
<option value="ti-jsfiddle">&lt;i class="ti-jsfiddle"&lt;/i> ti-jsfiddle </option>
<option value="ti-joomla">&lt;i class="ti-joomla"&lt;/i> ti-joomla </option>
<option value="ti-html5">&lt;i class="ti-html5"&lt;/i> ti-html5 </option>
<option value="ti-css3">&lt;i class="ti-css3"&lt;/i> ti-css3 </option>
<option value="ti-drupal">&lt;i class="ti-drupal"&lt;/i> ti-drupal </option>
<option value="ti-wordpress">&lt;i class="ti-wordpress"&lt;/i> ti-wordpress </option>
<option value="ti-tumblr">&lt;i class="ti-tumblr"&lt;/i> ti-tumblr </option>
<option value="ti-tumblr-alt">&lt;i class="ti-tumblr-alt"&lt;/i> ti-tumblr-alt </option>
<option value="ti-skype">&lt;i class="ti-skype"&lt;/i> ti-skype </option>
<option value="ti-youtube">&lt;i class="ti-youtube"&lt;/i> ti-youtube </option>
<option value="ti-vimeo">&lt;i class="ti-vimeo"&lt;/i> ti-vimeo </option>
<option value="ti-vimeo-alt">&lt;i class="ti-vimeo-alt"&lt;/i> ti-vimeo-alt </option>
<option value="ti-twitter">&lt;i class="ti-twitter"&lt;/i> ti-twitter </option>
<option value="ti-twitter-alt">&lt;i class="ti-twitter-alt"&lt;/i> ti-twitter-alt </option>
<option value="ti-linkedin">&lt;i class="ti-linkedin"&lt;/i> ti-linkedin </option>
<option value="ti-pinterest">&lt;i class="ti-pinterest"&lt;/i> ti-pinterest </option>
<option value="ti-pinterest-alt">&lt;i class="ti-pinterest-alt"&lt;/i> ti-pinterest-alt </option>
<option value="ti-themify-logo">&lt;i class="ti-themify-logo"&lt;/i> ti-themify-logo </option>
<option value="ti-themify-favicon">&lt;i class="ti-themify-favicon"&lt;/i> ti-themify-favicon </option>
<option value="ti-themify-favicon-alt">&lt;i class="ti-themify-favicon-alt"&lt;/i> ti-themify-favicon-alt </option>
';
echo $options;
