<?php

/* Glyphicon Icons List */
$options = ' 
<option value=""></option>
<option value="glyphicon glyphicon-asterisk">&lt;i class="glyphicon glyphicon-asterisk"&lt;/i> glyphicon-asterisk</option>
<option value="glyphicon glyphicon-plus">&lt;i class="glyphicon glyphicon-plus"&lt;/i> glyphicon-plus</option>
<option value="glyphicon glyphicon-minus">&lt;i class="glyphicon glyphicon-minus"&lt;/i> glyphicon-minus</option>
<option value="glyphicon glyphicon-eur">&lt;i class="glyphicon glyphicon-eur"&lt;/i> glyphicon-eur</option>
<option value="glyphicon glyphicon-euro">&lt;i class="glyphicon glyphicon-euro"&lt;/i> glyphicon-euro</option>
<option value="glyphicon glyphicon-cloud">&lt;i class="glyphicon glyphicon-cloud"&lt;/i> glyphicon-cloud</option>
<option value="glyphicon glyphicon-envelope">&lt;i class="glyphicon glyphicon-envelope"&lt;/i> glyphicon-envelope</option>
<option value="glyphicon glyphicon-pencil">&lt;i class="glyphicon glyphicon-pencil"&lt;/i> glyphicon-pencil</option>
<option value="glyphicon glyphicon-glass">&lt;i class="glyphicon glyphicon-glass"&lt;/i> glyphicon-glass</option>
<option value="glyphicon glyphicon-music">&lt;i class="glyphicon glyphicon-music"&lt;/i> glyphicon-music</option>
<option value="glyphicon glyphicon-search">&lt;i class="glyphicon glyphicon-search"&lt;/i> glyphicon-search</option>
<option value="glyphicon glyphicon-heart">&lt;i class="glyphicon glyphicon-heart"&lt;/i> glyphicon-heart</option>
<option value="glyphicon glyphicon-star">&lt;i class="glyphicon glyphicon-star"&lt;/i> glyphicon-star</option>
<option value="glyphicon glyphicon-star-empty">&lt;i class="glyphicon glyphicon-star-empty"&lt;/i> glyphicon-star-empty</option>
<option value="glyphicon glyphicon-user">&lt;i class="glyphicon glyphicon-user"&lt;/i> glyphicon-user</option>
<option value="glyphicon glyphicon-film">&lt;i class="glyphicon glyphicon-film"&lt;/i> glyphicon-film</option>
<option value="glyphicon glyphicon-th-large">&lt;i class="glyphicon glyphicon-th-large"&lt;/i> glyphicon-th-large</option>
<option value="glyphicon glyphicon-th">&lt;i class="glyphicon glyphicon-th"&lt;/i> glyphicon-th</option>
<option value="glyphicon glyphicon-th-list">&lt;i class="glyphicon glyphicon-th-list"&lt;/i> glyphicon-th-list</option>
<option value="glyphicon glyphicon-ok">&lt;i class="glyphicon glyphicon-ok"&lt;/i> glyphicon-ok</option>
<option value="glyphicon glyphicon-remove">&lt;i class="glyphicon glyphicon-remove"&lt;/i> glyphicon-remove</option>
<option value="glyphicon glyphicon-zoom-in">&lt;i class="glyphicon glyphicon-zoom-in"&lt;/i> glyphicon-zoom-in</option>
<option value="glyphicon glyphicon-zoom-out">&lt;i class="glyphicon glyphicon-zoom-out"&lt;/i> glyphicon-zoom-out</option>
<option value="glyphicon glyphicon-off">&lt;i class="glyphicon glyphicon-off"&lt;/i> glyphicon-off</option>
<option value="glyphicon glyphicon-signal">&lt;i class="glyphicon glyphicon-signal"&lt;/i> glyphicon-signal</option>
<option value="glyphicon glyphicon-cog">&lt;i class="glyphicon glyphicon-cog"&lt;/i> glyphicon-cog</option>
<option value="glyphicon glyphicon-trash">&lt;i class="glyphicon glyphicon-trash"&lt;/i> glyphicon-trash</option>
<option value="glyphicon glyphicon-home">&lt;i class="glyphicon glyphicon-home"&lt;/i> glyphicon-home</option>
<option value="glyphicon glyphicon-file">&lt;i class="glyphicon glyphicon-file"&lt;/i> glyphicon-file</option>
<option value="glyphicon glyphicon-time">&lt;i class="glyphicon glyphicon-time"&lt;/i> glyphicon-time</option>
<option value="glyphicon glyphicon-road">&lt;i class="glyphicon glyphicon-road"&lt;/i> glyphicon-road</option>
<option value="glyphicon glyphicon-download-alt">&lt;i class="glyphicon glyphicon-download-alt"&lt;/i> glyphicon-download-alt</option>
<option value="glyphicon glyphicon-download">&lt;i class="glyphicon glyphicon-download"&lt;/i> glyphicon-download</option>
<option value="glyphicon glyphicon-upload">&lt;i class="glyphicon glyphicon-upload"&lt;/i> glyphicon-upload</option>
<option value="glyphicon glyphicon-inbox">&lt;i class="glyphicon glyphicon-inbox"&lt;/i> glyphicon-inbox</option>
<option value="glyphicon glyphicon-play-circle">&lt;i class="glyphicon glyphicon-play-circle"&lt;/i> glyphicon-play-circle</option>
<option value="glyphicon glyphicon-repeat">&lt;i class="glyphicon glyphicon-repeat"&lt;/i> glyphicon-repeat</option>
<option value="glyphicon glyphicon-refresh">&lt;i class="glyphicon glyphicon-refresh"&lt;/i> glyphicon-refresh</option>
<option value="glyphicon glyphicon-list-alt">&lt;i class="glyphicon glyphicon-list-alt"&lt;/i> glyphicon-list-alt</option>
<option value="glyphicon glyphicon-lock">&lt;i class="glyphicon glyphicon-lock"&lt;/i> glyphicon-lock</option>
<option value="glyphicon glyphicon-flag">&lt;i class="glyphicon glyphicon-flag"&lt;/i> glyphicon-flag</option>
<option value="glyphicon glyphicon-headphones">&lt;i class="glyphicon glyphicon-headphones"&lt;/i> glyphicon-headphones</option>
<option value="glyphicon glyphicon-volume-off">&lt;i class="glyphicon glyphicon-volume-off"&lt;/i> glyphicon-volume-off</option>
<option value="glyphicon glyphicon-volume-down">&lt;i class="glyphicon glyphicon-volume-down"&lt;/i> glyphicon-volume-down</option>
<option value="glyphicon glyphicon-volume-up">&lt;i class="glyphicon glyphicon-volume-up"&lt;/i> glyphicon-volume-up</option>
<option value="glyphicon glyphicon-qrcode">&lt;i class="glyphicon glyphicon-qrcode"&lt;/i> glyphicon-qrcode</option>
<option value="glyphicon glyphicon-barcode">&lt;i class="glyphicon glyphicon-barcode"&lt;/i> glyphicon-barcode</option>
<option value="glyphicon glyphicon-tag">&lt;i class="glyphicon glyphicon-tag"&lt;/i> glyphicon-tag</option>
<option value="glyphicon glyphicon-tags">&lt;i class="glyphicon glyphicon-tags"&lt;/i> glyphicon-tags</option>
<option value="glyphicon glyphicon-book">&lt;i class="glyphicon glyphicon-book"&lt;/i> glyphicon-book</option>
<option value="glyphicon glyphicon-bookmark">&lt;i class="glyphicon glyphicon-bookmark"&lt;/i> glyphicon-bookmark</option>
<option value="glyphicon glyphicon-print">&lt;i class="glyphicon glyphicon-print"&lt;/i> glyphicon-print</option>
<option value="glyphicon glyphicon-camera">&lt;i class="glyphicon glyphicon-camera"&lt;/i> glyphicon-camera</option>
<option value="glyphicon glyphicon-font">&lt;i class="glyphicon glyphicon-font"&lt;/i> glyphicon-font</option>
<option value="glyphicon glyphicon-bold">&lt;i class="glyphicon glyphicon-bold"&lt;/i> glyphicon-bold</option>
<option value="glyphicon glyphicon-italic">&lt;i class="glyphicon glyphicon-italic"&lt;/i> glyphicon-italic</option>
<option value="glyphicon glyphicon-text-height">&lt;i class="glyphicon glyphicon-text-height"&lt;/i> glyphicon-text-height</option>
<option value="glyphicon glyphicon-text-width">&lt;i class="glyphicon glyphicon-text-width"&lt;/i> glyphicon-text-width</option>
<option value="glyphicon glyphicon-align-left">&lt;i class="glyphicon glyphicon-align-left"&lt;/i> glyphicon-align-left</option>
<option value="glyphicon glyphicon-align-center">&lt;i class="glyphicon glyphicon-align-center"&lt;/i> glyphicon-align-center</option>
<option value="glyphicon glyphicon-align-right">&lt;i class="glyphicon glyphicon-align-right"&lt;/i> glyphicon-align-right</option>
<option value="glyphicon glyphicon-align-justify">&lt;i class="glyphicon glyphicon-align-justify"&lt;/i> glyphicon-align-justify</option>
<option value="glyphicon glyphicon-list">&lt;i class="glyphicon glyphicon-list"&lt;/i> glyphicon-list</option>
<option value="glyphicon glyphicon-indent-left">&lt;i class="glyphicon glyphicon-indent-left"&lt;/i> glyphicon-indent-left</option>
<option value="glyphicon glyphicon-indent-right">&lt;i class="glyphicon glyphicon-indent-right"&lt;/i> glyphicon-indent-right</option>
<option value="glyphicon glyphicon-facetime-video">&lt;i class="glyphicon glyphicon-facetime-video"&lt;/i> glyphicon-facetime-video</option>
<option value="glyphicon glyphicon-picture">&lt;i class="glyphicon glyphicon-picture"&lt;/i> glyphicon-picture</option>
<option value="glyphicon glyphicon-map-marker">&lt;i class="glyphicon glyphicon-map-marker"&lt;/i> glyphicon-map-marker</option>
<option value="glyphicon glyphicon-adjust">&lt;i class="glyphicon glyphicon-adjust"&lt;/i> glyphicon-adjust</option>
<option value="glyphicon glyphicon-tint">&lt;i class="glyphicon glyphicon-tint"&lt;/i> glyphicon-tint</option>
<option value="glyphicon glyphicon-edit">&lt;i class="glyphicon glyphicon-edit"&lt;/i> glyphicon-edit</option>
<option value="glyphicon glyphicon-share">&lt;i class="glyphicon glyphicon-share"&lt;/i> glyphicon-share</option>
<option value="glyphicon glyphicon-check">&lt;i class="glyphicon glyphicon-check"&lt;/i> glyphicon-check</option>
<option value="glyphicon glyphicon-move">&lt;i class="glyphicon glyphicon-move"&lt;/i> glyphicon-move</option>
<option value="glyphicon glyphicon-step-backward">&lt;i class="glyphicon glyphicon-step-backward"&lt;/i> glyphicon-step-backward</option>
<option value="glyphicon glyphicon-fast-backward">&lt;i class="glyphicon glyphicon-fast-backward"&lt;/i> glyphicon-fast-backward</option>
<option value="glyphicon glyphicon-backward">&lt;i class="glyphicon glyphicon-backward"&lt;/i> glyphicon-backward</option>
<option value="glyphicon glyphicon-play">&lt;i class="glyphicon glyphicon-play"&lt;/i> glyphicon-play</option>
<option value="glyphicon glyphicon-pause">&lt;i class="glyphicon glyphicon-pause"&lt;/i> glyphicon-pause</option>
<option value="glyphicon glyphicon-stop">&lt;i class="glyphicon glyphicon-stop"&lt;/i> glyphicon-stop</option>
<option value="glyphicon glyphicon-forward">&lt;i class="glyphicon glyphicon-forward"&lt;/i> glyphicon-forward</option>
<option value="glyphicon glyphicon-fast-forward">&lt;i class="glyphicon glyphicon-fast-forward"&lt;/i> glyphicon-fast-forward</option>
<option value="glyphicon glyphicon-step-forward">&lt;i class="glyphicon glyphicon-step-forward"&lt;/i> glyphicon-step-forward</option>
<option value="glyphicon glyphicon-eject">&lt;i class="glyphicon glyphicon-eject"&lt;/i> glyphicon-eject</option>
<option value="glyphicon glyphicon-chevron-left">&lt;i class="glyphicon glyphicon-chevron-left"&lt;/i> glyphicon-chevron-left</option>
<option value="glyphicon glyphicon-chevron-right">&lt;i class="glyphicon glyphicon-chevron-right"&lt;/i> glyphicon-chevron-right</option>
<option value="glyphicon glyphicon-plus-sign">&lt;i class="glyphicon glyphicon-plus-sign"&lt;/i> glyphicon-plus-sign</option>
<option value="glyphicon glyphicon-minus-sign">&lt;i class="glyphicon glyphicon-minus-sign"&lt;/i> glyphicon-minus-sign</option>
<option value="glyphicon glyphicon-remove-sign">&lt;i class="glyphicon glyphicon-remove-sign"&lt;/i> glyphicon-remove-sign</option>
<option value="glyphicon glyphicon-ok-sign">&lt;i class="glyphicon glyphicon-ok-sign"&lt;/i> glyphicon-ok-sign</option>
<option value="glyphicon glyphicon-question-sign">&lt;i class="glyphicon glyphicon-question-sign"&lt;/i> glyphicon-question-sign</option>
<option value="glyphicon glyphicon-info-sign">&lt;i class="glyphicon glyphicon-info-sign"&lt;/i> glyphicon-info-sign</option>
<option value="glyphicon glyphicon-screenshot">&lt;i class="glyphicon glyphicon-screenshot"&lt;/i> glyphicon-screenshot</option>
<option value="glyphicon glyphicon-remove-circle">&lt;i class="glyphicon glyphicon-remove-circle"&lt;/i> glyphicon-remove-circle</option>
<option value="glyphicon glyphicon-ok-circle">&lt;i class="glyphicon glyphicon-ok-circle"&lt;/i> glyphicon-ok-circle</option>
<option value="glyphicon glyphicon-ban-circle">&lt;i class="glyphicon glyphicon-ban-circle"&lt;/i> glyphicon-ban-circle</option>
<option value="glyphicon glyphicon-arrow-left">&lt;i class="glyphicon glyphicon-arrow-left"&lt;/i> glyphicon-arrow-left</option>
<option value="glyphicon glyphicon-arrow-right">&lt;i class="glyphicon glyphicon-arrow-right"&lt;/i> glyphicon-arrow-right</option>
<option value="glyphicon glyphicon-arrow-up">&lt;i class="glyphicon glyphicon-arrow-up"&lt;/i> glyphicon-arrow-up</option>
<option value="glyphicon glyphicon-arrow-down">&lt;i class="glyphicon glyphicon-arrow-down"&lt;/i> glyphicon-arrow-down</option>
<option value="glyphicon glyphicon-share-alt">&lt;i class="glyphicon glyphicon-share-alt"&lt;/i> glyphicon-share-alt</option>
<option value="glyphicon glyphicon-resize-full">&lt;i class="glyphicon glyphicon-resize-full"&lt;/i> glyphicon-resize-full</option>
<option value="glyphicon glyphicon-resize-small">&lt;i class="glyphicon glyphicon-resize-small"&lt;/i> glyphicon-resize-small</option>
<option value="glyphicon glyphicon-exclamation-sign">&lt;i class="glyphicon glyphicon-exclamation-sign"&lt;/i> glyphicon-exclamation-sign</option>
<option value="glyphicon glyphicon-gift">&lt;i class="glyphicon glyphicon-gift"&lt;/i> glyphicon-gift</option>
<option value="glyphicon glyphicon-leaf">&lt;i class="glyphicon glyphicon-leaf"&lt;/i> glyphicon-leaf</option>
<option value="glyphicon glyphicon-fire">&lt;i class="glyphicon glyphicon-fire"&lt;/i> glyphicon-fire</option>
<option value="glyphicon glyphicon-eye-open">&lt;i class="glyphicon glyphicon-eye-open"&lt;/i> glyphicon-eye-open</option>
<option value="glyphicon glyphicon-eye-close">&lt;i class="glyphicon glyphicon-eye-close"&lt;/i> glyphicon-eye-close</option>
<option value="glyphicon glyphicon-warning-sign">&lt;i class="glyphicon glyphicon-warning-sign"&lt;/i> glyphicon-warning-sign</option>
<option value="glyphicon glyphicon-plane">&lt;i class="glyphicon glyphicon-plane"&lt;/i> glyphicon-plane</option>
<option value="glyphicon glyphicon-calendar">&lt;i class="glyphicon glyphicon-calendar"&lt;/i> glyphicon-calendar</option>
<option value="glyphicon glyphicon-random">&lt;i class="glyphicon glyphicon-random"&lt;/i> glyphicon-random</option>
<option value="glyphicon glyphicon-comment">&lt;i class="glyphicon glyphicon-comment"&lt;/i> glyphicon-comment</option>
<option value="glyphicon glyphicon-magnet">&lt;i class="glyphicon glyphicon-magnet"&lt;/i> glyphicon-magnet</option>
<option value="glyphicon glyphicon-chevron-up">&lt;i class="glyphicon glyphicon-chevron-up"&lt;/i> glyphicon-chevron-up</option>
<option value="glyphicon glyphicon-chevron-down">&lt;i class="glyphicon glyphicon-chevron-down"&lt;/i> glyphicon-chevron-down</option>
<option value="glyphicon glyphicon-retweet">&lt;i class="glyphicon glyphicon-retweet"&lt;/i> glyphicon-retweet</option>
<option value="glyphicon glyphicon-shopping-cart">&lt;i class="glyphicon glyphicon-shopping-cart"&lt;/i> glyphicon-shopping-cart</option>
<option value="glyphicon glyphicon-folder-close">&lt;i class="glyphicon glyphicon-folder-close"&lt;/i> glyphicon-folder-close</option>
<option value="glyphicon glyphicon-folder-open">&lt;i class="glyphicon glyphicon-folder-open"&lt;/i> glyphicon-folder-open</option>
<option value="glyphicon glyphicon-resize-vertical">&lt;i class="glyphicon glyphicon-resize-vertical"&lt;/i> glyphicon-resize-vertical</option>
<option value="glyphicon glyphicon-resize-horizontal">&lt;i class="glyphicon glyphicon-resize-horizontal"&lt;/i> glyphicon-resize-horizontal</option>
<option value="glyphicon glyphicon-hdd">&lt;i class="glyphicon glyphicon-hdd"&lt;/i> glyphicon-hdd</option>
<option value="glyphicon glyphicon-bullhorn">&lt;i class="glyphicon glyphicon-bullhorn"&lt;/i> glyphicon-bullhorn</option>
<option value="glyphicon glyphicon-bell">&lt;i class="glyphicon glyphicon-bell"&lt;/i> glyphicon-bell</option>
<option value="glyphicon glyphicon-certificate">&lt;i class="glyphicon glyphicon-certificate"&lt;/i> glyphicon-certificate</option>
<option value="glyphicon glyphicon-thumbs-up">&lt;i class="glyphicon glyphicon-thumbs-up"&lt;/i> glyphicon-thumbs-up</option>
<option value="glyphicon glyphicon-thumbs-down">&lt;i class="glyphicon glyphicon-thumbs-down"&lt;/i> glyphicon-thumbs-down</option>
<option value="glyphicon glyphicon-hand-right">&lt;i class="glyphicon glyphicon-hand-right"&lt;/i> glyphicon-hand-right</option>
<option value="glyphicon glyphicon-hand-left">&lt;i class="glyphicon glyphicon-hand-left"&lt;/i> glyphicon-hand-left</option>
<option value="glyphicon glyphicon-hand-up">&lt;i class="glyphicon glyphicon-hand-up"&lt;/i> glyphicon-hand-up</option>
<option value="glyphicon glyphicon-hand-down">&lt;i class="glyphicon glyphicon-hand-down"&lt;/i> glyphicon-hand-down</option>
<option value="glyphicon glyphicon-circle-arrow-right">&lt;i class="glyphicon glyphicon-circle-arrow-right"&lt;/i> glyphicon-circle-arrow-right</option>
<option value="glyphicon glyphicon-circle-arrow-left">&lt;i class="glyphicon glyphicon-circle-arrow-left"&lt;/i> glyphicon-circle-arrow-left</option>
<option value="glyphicon glyphicon-circle-arrow-up">&lt;i class="glyphicon glyphicon-circle-arrow-up"&lt;/i> glyphicon-circle-arrow-up</option>
<option value="glyphicon glyphicon-circle-arrow-down">&lt;i class="glyphicon glyphicon-circle-arrow-down"&lt;/i> glyphicon-circle-arrow-down</option>
<option value="glyphicon glyphicon-globe">&lt;i class="glyphicon glyphicon-globe"&lt;/i> glyphicon-globe</option>
<option value="glyphicon glyphicon-wrench">&lt;i class="glyphicon glyphicon-wrench"&lt;/i> glyphicon-wrench</option>
<option value="glyphicon glyphicon-tasks">&lt;i class="glyphicon glyphicon-tasks"&lt;/i> glyphicon-tasks</option>
<option value="glyphicon glyphicon-filter">&lt;i class="glyphicon glyphicon-filter"&lt;/i> glyphicon-filter</option>
<option value="glyphicon glyphicon-briefcase">&lt;i class="glyphicon glyphicon-briefcase"&lt;/i> glyphicon-briefcase</option>
<option value="glyphicon glyphicon-fullscreen">&lt;i class="glyphicon glyphicon-fullscreen"&lt;/i> glyphicon-fullscreen</option>
<option value="glyphicon glyphicon-dashboard">&lt;i class="glyphicon glyphicon-dashboard"&lt;/i> glyphicon-dashboard</option>
<option value="glyphicon glyphicon-paperclip">&lt;i class="glyphicon glyphicon-paperclip"&lt;/i> glyphicon-paperclip</option>
<option value="glyphicon glyphicon-heart-empty">&lt;i class="glyphicon glyphicon-heart-empty"&lt;/i> glyphicon-heart-empty</option>
<option value="glyphicon glyphicon-link">&lt;i class="glyphicon glyphicon-link"&lt;/i> glyphicon-link</option>
<option value="glyphicon glyphicon-phone">&lt;i class="glyphicon glyphicon-phone"&lt;/i> glyphicon-phone</option>
<option value="glyphicon glyphicon-pushpin">&lt;i class="glyphicon glyphicon-pushpin"&lt;/i> glyphicon-pushpin</option>
<option value="glyphicon glyphicon-usd">&lt;i class="glyphicon glyphicon-usd"&lt;/i> glyphicon-usd</option>
<option value="glyphicon glyphicon-gbp">&lt;i class="glyphicon glyphicon-gbp"&lt;/i> glyphicon-gbp</option>
<option value="glyphicon glyphicon-sort">&lt;i class="glyphicon glyphicon-sort"&lt;/i> glyphicon-sort</option>
<option value="glyphicon glyphicon-sort-by-alphabet">&lt;i class="glyphicon glyphicon-sort-by-alphabet"&lt;/i> glyphicon-sort-by-alphabet</option>
<option value="glyphicon glyphicon-sort-by-alphabet-alt">&lt;i class="glyphicon glyphicon-sort-by-alphabet-alt"&lt;/i> glyphicon-sort-by-alphabet-alt</option>
<option value="glyphicon glyphicon-sort-by-order">&lt;i class="glyphicon glyphicon-sort-by-order"&lt;/i> glyphicon-sort-by-order</option>
<option value="glyphicon glyphicon-sort-by-order-alt">&lt;i class="glyphicon glyphicon-sort-by-order-alt"&lt;/i> glyphicon-sort-by-order-alt</option>
<option value="glyphicon glyphicon-sort-by-attributes">&lt;i class="glyphicon glyphicon-sort-by-attributes"&lt;/i> glyphicon-sort-by-attributes</option>
<option value="glyphicon glyphicon-sort-by-attributes-alt">&lt;i class="glyphicon glyphicon-sort-by-attributes-alt"&lt;/i> glyphicon-sort-by-attributes-alt</option>
<option value="glyphicon glyphicon-unchecked">&lt;i class="glyphicon glyphicon-unchecked"&lt;/i> glyphicon-unchecked</option>
<option value="glyphicon glyphicon-expand">&lt;i class="glyphicon glyphicon-expand"&lt;/i> glyphicon-expand</option>
<option value="glyphicon glyphicon-collapse-down">&lt;i class="glyphicon glyphicon-collapse-down"&lt;/i> glyphicon-collapse-down</option>
<option value="glyphicon glyphicon-collapse-up">&lt;i class="glyphicon glyphicon-collapse-up"&lt;/i> glyphicon-collapse-up</option>
<option value="glyphicon glyphicon-log-in">&lt;i class="glyphicon glyphicon-log-in"&lt;/i> glyphicon-log-in</option>
<option value="glyphicon glyphicon-flash">&lt;i class="glyphicon glyphicon-flash"&lt;/i> glyphicon-flash</option>
<option value="glyphicon glyphicon-log-out">&lt;i class="glyphicon glyphicon-log-out"&lt;/i> glyphicon-log-out</option>
<option value="glyphicon glyphicon-new-window">&lt;i class="glyphicon glyphicon-new-window"&lt;/i> glyphicon-new-window</option>
<option value="glyphicon glyphicon-record">&lt;i class="glyphicon glyphicon-record"&lt;/i> glyphicon-record</option>
<option value="glyphicon glyphicon-save">&lt;i class="glyphicon glyphicon-save"&lt;/i> glyphicon-save</option>
<option value="glyphicon glyphicon-open">&lt;i class="glyphicon glyphicon-open"&lt;/i> glyphicon-open</option>
<option value="glyphicon glyphicon-saved">&lt;i class="glyphicon glyphicon-saved"&lt;/i> glyphicon-saved</option>
<option value="glyphicon glyphicon-import">&lt;i class="glyphicon glyphicon-import"&lt;/i> glyphicon-import</option>
<option value="glyphicon glyphicon-export">&lt;i class="glyphicon glyphicon-export"&lt;/i> glyphicon-export</option>
<option value="glyphicon glyphicon-send">&lt;i class="glyphicon glyphicon-send"&lt;/i> glyphicon-send</option>
<option value="glyphicon glyphicon-floppy-disk">&lt;i class="glyphicon glyphicon-floppy-disk"&lt;/i> glyphicon-floppy-disk</option>
<option value="glyphicon glyphicon-floppy-saved">&lt;i class="glyphicon glyphicon-floppy-saved"&lt;/i> glyphicon-floppy-saved</option>
<option value="glyphicon glyphicon-floppy-remove">&lt;i class="glyphicon glyphicon-floppy-remove"&lt;/i> glyphicon-floppy-remove</option>
<option value="glyphicon glyphicon-floppy-save">&lt;i class="glyphicon glyphicon-floppy-save"&lt;/i> glyphicon-floppy-save</option>
<option value="glyphicon glyphicon-floppy-open">&lt;i class="glyphicon glyphicon-floppy-open"&lt;/i> glyphicon-floppy-open</option>
<option value="glyphicon glyphicon-credit-card">&lt;i class="glyphicon glyphicon-credit-card"&lt;/i> glyphicon-credit-card</option>
<option value="glyphicon glyphicon-transfer">&lt;i class="glyphicon glyphicon-transfer"&lt;/i> glyphicon-transfer</option>
<option value="glyphicon glyphicon-cutlery">&lt;i class="glyphicon glyphicon-cutlery"&lt;/i> glyphicon-cutlery</option>
<option value="glyphicon glyphicon-header">&lt;i class="glyphicon glyphicon-header"&lt;/i> glyphicon-header</option>
<option value="glyphicon glyphicon-compressed">&lt;i class="glyphicon glyphicon-compressed"&lt;/i> glyphicon-compressed</option>
<option value="glyphicon glyphicon-earphone">&lt;i class="glyphicon glyphicon-earphone"&lt;/i> glyphicon-earphone</option>
<option value="glyphicon glyphicon-phone-alt">&lt;i class="glyphicon glyphicon-phone-alt"&lt;/i> glyphicon-phone-alt</option>
<option value="glyphicon glyphicon-tower">&lt;i class="glyphicon glyphicon-tower"&lt;/i> glyphicon-tower</option>
<option value="glyphicon glyphicon-stats">&lt;i class="glyphicon glyphicon-stats"&lt;/i> glyphicon-stats</option>
<option value="glyphicon glyphicon-sd-video">&lt;i class="glyphicon glyphicon-sd-video"&lt;/i> glyphicon-sd-video</option>
<option value="glyphicon glyphicon-hd-video">&lt;i class="glyphicon glyphicon-hd-video"&lt;/i> glyphicon-hd-video</option>
<option value="glyphicon glyphicon-subtitles">&lt;i class="glyphicon glyphicon-subtitles"&lt;/i> glyphicon-subtitles</option>
<option value="glyphicon glyphicon-sound-stereo">&lt;i class="glyphicon glyphicon-sound-stereo"&lt;/i> glyphicon-sound-stereo</option>
<option value="glyphicon glyphicon-sound-dolby">&lt;i class="glyphicon glyphicon-sound-dolby"&lt;/i> glyphicon-sound-dolby</option>
<option value="glyphicon glyphicon-sound-5-1">&lt;i class="glyphicon glyphicon-sound-5-1"&lt;/i> glyphicon-sound-5-1</option>
<option value="glyphicon glyphicon-sound-6-1">&lt;i class="glyphicon glyphicon-sound-6-1"&lt;/i> glyphicon-sound-6-1</option>
<option value="glyphicon glyphicon-sound-7-1">&lt;i class="glyphicon glyphicon-sound-7-1"&lt;/i> glyphicon-sound-7-1</option>
<option value="glyphicon glyphicon-copyright-mark">&lt;i class="glyphicon glyphicon-copyright-mark"&lt;/i> glyphicon-copyright-mark</option>
<option value="glyphicon glyphicon-registration-mark">&lt;i class="glyphicon glyphicon-registration-mark"&lt;/i> glyphicon-registration-mark</option>
<option value="glyphicon glyphicon-cloud-download">&lt;i class="glyphicon glyphicon-cloud-download"&lt;/i> glyphicon-cloud-download</option>
<option value="glyphicon glyphicon-cloud-upload">&lt;i class="glyphicon glyphicon-cloud-upload"&lt;/i> glyphicon-cloud-upload</option>
<option value="glyphicon glyphicon-tree-conifer">&lt;i class="glyphicon glyphicon-tree-conifer"&lt;/i> glyphicon-tree-conifer</option>
<option value="glyphicon glyphicon-tree-deciduous">&lt;i class="glyphicon glyphicon-tree-deciduous"&lt;/i> glyphicon-tree-deciduous</option>
<option value="glyphicon glyphicon-cd">&lt;i class="glyphicon glyphicon-cd"&lt;/i> glyphicon-cd</option>
<option value="glyphicon glyphicon-save-file">&lt;i class="glyphicon glyphicon-save-file"&lt;/i> glyphicon-save-file</option>
<option value="glyphicon glyphicon-open-file">&lt;i class="glyphicon glyphicon-open-file"&lt;/i> glyphicon-open-file</option>
<option value="glyphicon glyphicon-level-up">&lt;i class="glyphicon glyphicon-level-up"&lt;/i> glyphicon-level-up</option>
<option value="glyphicon glyphicon-copy">&lt;i class="glyphicon glyphicon-copy"&lt;/i> glyphicon-copy</option>
<option value="glyphicon glyphicon-paste">&lt;i class="glyphicon glyphicon-paste"&lt;/i> glyphicon-paste</option>
<option value="glyphicon glyphicon-alert">&lt;i class="glyphicon glyphicon-alert"&lt;/i> glyphicon-alert</option>
<option value="glyphicon glyphicon-equalizer">&lt;i class="glyphicon glyphicon-equalizer"&lt;/i> glyphicon-equalizer</option>
<option value="glyphicon glyphicon-king">&lt;i class="glyphicon glyphicon-king"&lt;/i> glyphicon-king</option>
<option value="glyphicon glyphicon-queen">&lt;i class="glyphicon glyphicon-queen"&lt;/i> glyphicon-queen</option>
<option value="glyphicon glyphicon-pawn">&lt;i class="glyphicon glyphicon-pawn"&lt;/i> glyphicon-pawn</option>
<option value="glyphicon glyphicon-bishop">&lt;i class="glyphicon glyphicon-bishop"&lt;/i> glyphicon-bishop</option>
<option value="glyphicon glyphicon-knight">&lt;i class="glyphicon glyphicon-knight"&lt;/i> glyphicon-knight</option>
<option value="glyphicon glyphicon-baby-formula">&lt;i class="glyphicon glyphicon-baby-formula"&lt;/i> glyphicon-baby-formula</option>
<option value="glyphicon glyphicon-tent">&lt;i class="glyphicon glyphicon-tent"&lt;/i> glyphicon-tent</option>
<option value="glyphicon glyphicon-blackboard">&lt;i class="glyphicon glyphicon-blackboard"&lt;/i> glyphicon-blackboard</option>
<option value="glyphicon glyphicon-bed">&lt;i class="glyphicon glyphicon-bed"&lt;/i> glyphicon-bed</option>
<option value="glyphicon glyphicon-apple">&lt;i class="glyphicon glyphicon-apple"&lt;/i> glyphicon-apple</option>
<option value="glyphicon glyphicon-erase">&lt;i class="glyphicon glyphicon-erase"&lt;/i> glyphicon-erase</option>
<option value="glyphicon glyphicon-hourglass">&lt;i class="glyphicon glyphicon-hourglass"&lt;/i> glyphicon-hourglass</option>
<option value="glyphicon glyphicon-lamp">&lt;i class="glyphicon glyphicon-lamp"&lt;/i> glyphicon-lamp</option>
<option value="glyphicon glyphicon-duplicate">&lt;i class="glyphicon glyphicon-duplicate"&lt;/i> glyphicon-duplicate</option>
<option value="glyphicon glyphicon-piggy-bank">&lt;i class="glyphicon glyphicon-piggy-bank"&lt;/i> glyphicon-piggy-bank</option>
<option value="glyphicon glyphicon-scissors">&lt;i class="glyphicon glyphicon-scissors"&lt;/i> glyphicon-scissors</option>
<option value="glyphicon glyphicon-bitcoin">&lt;i class="glyphicon glyphicon-bitcoin"&lt;/i> glyphicon-bitcoin</option>
<option value="glyphicon glyphicon-yen">&lt;i class="glyphicon glyphicon-yen"&lt;/i> glyphicon-yen</option>
<option value="glyphicon glyphicon-ruble">&lt;i class="glyphicon glyphicon-ruble"&lt;/i> glyphicon-ruble</option>
<option value="glyphicon glyphicon-scale">&lt;i class="glyphicon glyphicon-scale"&lt;/i> glyphicon-scale</option>
<option value="glyphicon glyphicon-ice-lolly">&lt;i class="glyphicon glyphicon-ice-lolly"&lt;/i> glyphicon-ice-lolly</option>
<option value="glyphicon glyphicon-ice-lolly-tasted">&lt;i class="glyphicon glyphicon-ice-lolly-tasted"&lt;/i> glyphicon-ice-lolly-tasted</option>
<option value="glyphicon glyphicon-education">&lt;i class="glyphicon glyphicon-education"&lt;/i> glyphicon-education</option>
<option value="glyphicon glyphicon-option-horizontal">&lt;i class="glyphicon glyphicon-option-horizontal"&lt;/i> glyphicon-option-horizontal</option>
<option value="glyphicon glyphicon-option-vertical">&lt;i class="glyphicon glyphicon-option-vertical"&lt;/i> glyphicon-option-vertical</option>
<option value="glyphicon glyphicon-menu-hamburger">&lt;i class="glyphicon glyphicon-menu-hamburger"&lt;/i> glyphicon-menu-hamburger</option>
<option value="glyphicon glyphicon-modal-window">&lt;i class="glyphicon glyphicon-modal-window"&lt;/i> glyphicon-modal-window</option>
<option value="glyphicon glyphicon-oil">&lt;i class="glyphicon glyphicon-oil"&lt;/i> glyphicon-oil</option>
<option value="glyphicon glyphicon-grain">&lt;i class="glyphicon glyphicon-grain"&lt;/i> glyphicon-grain</option>
<option value="glyphicon glyphicon-sunglasses">&lt;i class="glyphicon glyphicon-sunglasses"&lt;/i> glyphicon-sunglasses</option>
<option value="glyphicon glyphicon-text-size">&lt;i class="glyphicon glyphicon-text-size"&lt;/i> glyphicon-text-size</option>
<option value="glyphicon glyphicon-text-color">&lt;i class="glyphicon glyphicon-text-color"&lt;/i> glyphicon-text-color</option>
<option value="glyphicon glyphicon-text-background">&lt;i class="glyphicon glyphicon-text-background"&lt;/i> glyphicon-text-background</option>
<option value="glyphicon glyphicon-object-align-top">&lt;i class="glyphicon glyphicon-object-align-top"&lt;/i> glyphicon-object-align-top</option>
<option value="glyphicon glyphicon-object-align-bottom">&lt;i class="glyphicon glyphicon-object-align-bottom"&lt;/i> glyphicon-object-align-bottom</option>
<option value="glyphicon glyphicon-object-align-horizontal">&lt;i class="glyphicon glyphicon-object-align-horizontal"&lt;/i> glyphicon-object-align-horizontal</option>
<option value="glyphicon glyphicon-object-align-left">&lt;i class="glyphicon glyphicon-object-align-left"&lt;/i> glyphicon-object-align-left</option>
<option value="glyphicon glyphicon-object-align-vertical">&lt;i class="glyphicon glyphicon-object-align-vertical"&lt;/i> glyphicon-object-align-vertical</option>
<option value="glyphicon glyphicon-object-align-right">&lt;i class="glyphicon glyphicon-object-align-right"&lt;/i> glyphicon-object-align-right</option>
<option value="glyphicon glyphicon-triangle-right">&lt;i class="glyphicon glyphicon-triangle-right"&lt;/i> glyphicon-triangle-right</option>
<option value="glyphicon glyphicon-triangle-left">&lt;i class="glyphicon glyphicon-triangle-left"&lt;/i> glyphicon-triangle-left</option>
<option value="glyphicon glyphicon-triangle-bottom">&lt;i class="glyphicon glyphicon-triangle-bottom"&lt;/i> glyphicon-triangle-bottom</option>
<option value="glyphicon glyphicon-triangle-top">&lt;i class="glyphicon glyphicon-triangle-top"&lt;/i> glyphicon-triangle-top</option>
<option value="glyphicon glyphicon-console">&lt;i class="glyphicon glyphicon-console"&lt;/i> glyphicon-console</option>
<option value="glyphicon glyphicon-superscript">&lt;i class="glyphicon glyphicon-superscript"&lt;/i> glyphicon-superscript</option>
<option value="glyphicon glyphicon-subscript">&lt;i class="glyphicon glyphicon-subscript"&lt;/i> glyphicon-subscript</option>
<option value="glyphicon glyphicon-menu-left">&lt;i class="glyphicon glyphicon-menu-left"&lt;/i> glyphicon-menu-left</option>
<option value="glyphicon glyphicon-menu-right">&lt;i class="glyphicon glyphicon-menu-right"&lt;/i> glyphicon-menu-right</option>
<option value="glyphicon glyphicon-menu-down">&lt;i class="glyphicon glyphicon-menu-down"&lt;/i> glyphicon-menu-down</option>
<option value="glyphicon glyphicon-menu-up">&lt;i class="glyphicon glyphicon-menu-up"&lt;/i> glyphicon-menu-up</option>
';
echo $options;
